MONGO_CONNECTION_STRING: mongodb://localhost:26000
MONGO_DATABASE_NAME: Price

DATABASE_ZONE_COLLECTIONS: { "AR": "ARPrices","US": "USPrices" }
DATABASE_ZONE_COLLECTIONS_V2: { "AR": "ARPrices_V2","US": "USPrices_V2", "BR": "BRPrices_V2" }
UPCOMING_PRICES_COUNTRIES: AR